version: '3.8'

services:
  markmap-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 构建参数
        BUILD_ENV: ${BUILD_ENV:-production}
    container_name: markmap-service
    restart: unless-stopped
    ports:
      - "${PORT:-5003}:5003"
    volumes:
      - ${DATA_VOLUME:-./data}:/app/data
    environment:
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:5003}
      - HOST=0.0.0.0
      - PORT=5003
      - FILE_EXPIRY_HOURS=${FILE_EXPIRY_HOURS:-24}
      - CLEANUP_INTERVAL_HOURS=${CLEANUP_INTERVAL_HOURS:-1}
      - MAX_WORKERS=${MAX_WORKERS:-4}
      - DATA_DIR=/app/data
      # 增加JVM和Chromium内存限制
      - NODE_OPTIONS=--max_old_space_size=${NODE_MEMORY:-256}
      - CHROMIUM_FLAGS=--disable-dev-shm-usage --disable-gpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-1}'
          memory: ${MEMORY_LIMIT:-1G}
        reservations:
          cpus: '${CPU_RESERVE:-0.1}'
          memory: ${MEMORY_RESERVE:-128M}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    # 增加共享内存大小限制，提高Chromium性能
    shm_size: ${SHM_SIZE:-256M} 